### ISSUE TITLE
Kill whole process tree?

### ISSUE THREAD

**Issue by lucaswxp** [x13machine/ubuntu-demon-creator#2]
Hey nice script.

I'm having trouble using it for my case tho. I have a shell script like this:

myservice.sh:
```
#!/bin/bash
# do things here
./call_another_shell_script.sh
```

When I call `service myservice stop`, it's stopping only `myservice.sh`, but the inner `call_another_shell_script.sh` continues running. How can I handle this situation?

Regards

**Comment by x13machine** [comment]
killall -u <user> should work. In the /etc/init.d file maybe change the kill arguments

**Comment by x13machine** [comment]
I fixed it

**Comment by lucaswxp** [comment]
Nice work! Will try.
